# 히든레이어

- 보스턴 집값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv

- 아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv 


In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

## 보스턴 집값 예측

In [43]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [44]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
H2 = tf.keras.layers.Dense(10, activation='swish')(H)
H3 = tf.keras.layers.Dense(10, activation='swish')(H2)
Y = tf.keras.layers.Dense(1)(H3)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [45]:
# 모델 구조 확인
model.summary()

Model: "functional_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_8 (InputLayer)      │ (None, 13)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 10)             │           140 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 371 (1.45 KB)

 Trainable params: 371 (1.45 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=5)

Epoch 1/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 340us/step - loss: 6.3879
Epoch 2/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 295us/step - loss: 6.5481
Epoch 3/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - loss: 7.6628
Epoch 4/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - loss: 5.9977
Epoch 5/5
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - loss: 7.1364


In [51]:
# 4. 모델을 이용합니다
print(model.predict(독립[10:15]))
print(종속[10:15])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
[[17.954313]
 [19.972479]
 [19.20605 ]
 [19.391691]
 [18.280529]]
    medv
10  15.0
11  18.9
12  21.7
13  20.4
14  18.2


## 아이리스 품종 분류


In [32]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [34]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics=['accuracy'])

In [35]:
# 모델 구조 확인
model.summary()

Model: "functional_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_6 (InputLayer)      │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 211 (844.00 B)

 Trainable params: 211 (844.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 640us/step - accuracy: 0.9894 - loss: 0.0603
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 552us/step - accuracy: 0.9738 - loss: 0.0825
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - accuracy: 0.9633 - loss: 0.0849
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - accuracy: 0.9799 - loss: 0.0693
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - accuracy: 0.9798 - loss: 0.0688
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9811 - loss: 0.0627
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - accuracy: 0.9703 - loss: 0.0817
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.9746 - loss: 0.0732
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - accuracy: 0.9650 - loss: 0.0722
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - accuracy: 0.9685 - loss: 0.0716
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.9677 - loss: 0.0877
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy:

In [39]:
# 4. 모델을 이용합니다
print(model.predict(독립[0:5]))
print(종속[0:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[[9.99846160e-01 1.19745935e-04 3.40623592e-05]
 [9.99685764e-01 2.28575140e-04 8.57234481e-05]
 [9.99708176e-01 2.25175565e-04 6.66789274e-05]
 [9.99630928e-01 3.34482203e-04 3.45869958e-05]
 [9.99850869e-01 1.24766389e-04 2.42662700e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0       True          False         False
1       True          False         False
2       True          False         False
3       True          False         False
4       True          False         False
